In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('E:\\7th sem\\ML-LAB\\ML_lab_7th-Sem-main\\ML_lab_7th-Sem-main\\zoo.csv')

In [3]:
df

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
96      wallaby     1         0     0     1         0        0         0   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  class_type  
0          1           1  
1          1           1  
2          0           4  
3          1           1  
4          1           1  
..       ...         ...  
96         1           1  
97         0           6  
98         1           1  
99         0           7  
100        0           2  

[101 rows x 18 columns]

In [4]:
labels=df.columns.tolist()


In [5]:
labels

['animal_name',
 'hair',
 'feathers',
 'eggs',
 'milk',
 'airborne',
 'aquatic',
 'predator',
 'toothed',
 'backbone',
 'breathes',
 'venomous',
 'fins',
 'legs',
 'tail',
 'domestic',
 'catsize',
 'class_type']

In [6]:
x=df[labels[1:-1]]
y=df[labels[-1:]]

In [7]:
x

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0           1         1         0     0     4     0         0        1  
1           1         1         0     0     4     1         0        1  
2           1         0         0     1     0     1         0        0  
3           1         1         0     0     4     0         0        1  
4           1         1         0     0     4     1         0        1  
..        ...       ...       ...   ...   ...   ...       ...      ...  
96          1         1         0     0     2     1         0        1  
97          0         1         1     0     6     0         0        0  
98          1         1         0     0     4     1         0        1  
99          0         1         0     0     0     0         0        0  
100         1         1         0     0     2     1         0        0  

[101 rows x 16 columns]

In [8]:
y

class_type
0             1
1             1
2             4
3             1
4             1
..          ...
96            1
97            6
98            1
99            7
100           2

[101 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [11]:
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)

In [12]:
y_pred

array([1, 7, 1, 7, 7, 6, 3, 1, 6, 1, 2, 1, 1, 1, 2, 1, 1, 2, 3, 2, 6, 1,
       2, 1, 1, 2], dtype=int64)

In [13]:
print(accuracy_score(y_test,y_pred))

0.9615384615384616


In [14]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         6
           3       0.50      1.00      0.67         1
           5       0.00      0.00      0.00         1
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         3

    accuracy                           0.96        26
   macro avg       0.75      0.83      0.78        26
weighted avg       0.94      0.96      0.95        26



C:\Users\Asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
print(confusion_matrix(y_test,y_pred))

[[12  0  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  3]]


In [16]:
actual_class=list(y_test['class_type'])

In [17]:
actual_class

[1, 7, 1, 7, 7, 6, 5, 1, 6, 1, 2, 1, 1, 1, 2, 1, 1, 2, 3, 2, 6, 1, 2, 1, 1, 2]

In [18]:
pred_class=list(y_pred)

In [19]:
pred_class

[1, 7, 1, 7, 7, 6, 3, 1, 6, 1, 2, 1, 1, 1, 2, 1, 1, 2, 3, 2, 6, 1, 2, 1, 1, 2]

In [20]:
for i in range(len(actual_class)):
    print("Actual class =",actual_class[i]," Predicted class = ",pred_class[i])

Actual class = 1  Predicted class =  1
Actual class = 7  Predicted class =  7
Actual class = 1  Predicted class =  1
Actual class = 7  Predicted class =  7
Actual class = 7  Predicted class =  7
Actual class = 6  Predicted class =  6
Actual class = 5  Predicted class =  3
Actual class = 1  Predicted class =  1
Actual class = 6  Predicted class =  6
Actual class = 1  Predicted class =  1
Actual class = 2  Predicted class =  2
Actual class = 1  Predicted class =  1
Actual class = 1  Predicted class =  1
Actual class = 1  Predicted class =  1
Actual class = 2  Predicted class =  2
Actual class = 1  Predicted class =  1
Actual class = 1  Predicted class =  1
Actual class = 2  Predicted class =  2
Actual class = 3  Predicted class =  3
Actual class = 2  Predicted class =  2
Actual class = 6  Predicted class =  6
Actual class = 1  Predicted class =  1
Actual class = 2  Predicted class =  2
Actual class = 1  Predicted class =  1
Actual class = 1  Predicted class =  1
Actual class = 2  Predict

In [21]:
print(accuracy_score(actual_class,pred_class))

0.9615384615384616
